### ISSUE TITLE
Add a .gitignore file to get rid of your DS_Store files

### ISSUE THREAD

**Issue by Paulinakhew** [bikramjitnarwal/ExamPrep#2]
- [ ] Write `find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch` in your terminal
  - this will untrack the DS_Store files in your repo
- [ ] Create a file in your root directory called `.gitignore`
- [ ] Add `**/.DS_Store` into that file
  - this will stop GitHub from tracking these files in the future

**Comment by bikramjitnarwal** [comment]
Thanks :)
